### ISSUE TITLE
IconBar

### ISSUE THREAD

**Issue by PazAutumn** [PazAutumn/BikeSantiago#8]

**Comment by AriellaRogueN** [comment]
Al colocar los tabs, me aparece el siguiente error,  Module not found: Can't resolve 'material-ui/FontIcon' , lo  mismo con el otro elemento

**Comment by PazAutumn** [comment]
tienes que importar las cosas que instalamos, revisa en los projects en la parte de datos los links de la documentación, ahí salen los imports para que los pegues en tus componentes

**Comment by AriellaRogueN** [comment]
Si esta todo importado, clone de nuevo el repositorio, ahora estoy probando...

**Comment by PazAutumn** [comment]
hiciste npm install?

**Comment by AriellaRogueN** [comment]
Si.       No funciona Material Ui .     Probé con Bootstrap y si funciona pero no hay iconos acordes  y las tabs son feas, estoy viendo en fontawesome.

**Comment by PazAutumn** [comment]
A mi tampoco me funciona, estoy tratando de arreglarlo

**Comment by PazAutumn** [comment]
@AriellaRogueN corre este comando  en la terminal y te va a funcionar material-ui `npm install material-ui@latest`
